In [1]:
my_list = [1,2,3,4,5]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
my_mat = [[1,2,3],[4,5,6],[8,7,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 9]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(4)

array([0.48726974, 0.2220048 , 0.67445602, 0.02927514])

In [17]:
np.random.randn(4,4)

array([[ 0.52227853,  0.34668309, -0.51393448, -0.73535266],
       [-0.04590719,  0.91771694, -0.84373797,  0.8447496 ],
       [ 0.11279254,  0.26141199, -1.39811089, -0.66552731],
       [ 1.09080934, -1.04136684, -1.59184908,  0.4448462 ]])

In [23]:
np.random.randint(20, 100,4)

array([58, 70, 40, 63])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
rarr = arr.reshape(5,5)

In [31]:
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
rarr.min()

0

In [33]:
rarr.max()

24

In [34]:
rarr.argmax()

24

In [35]:
rarr.argmin()

0

In [40]:
rarr = rarr.reshape(5,5)

In [42]:
rarr.shape

(5, 5)

In [43]:
rarr.dtype

dtype('int64')

In [44]:
from numpy.random import randint

In [45]:
randint(4)

3