In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr [0:5] = 100 #Broadcase the value to whole list

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
sa = arr[0:6]

In [13]:
sa

array([0, 1, 2, 3, 4, 5])

In [14]:
sa[:] = 3

In [15]:
sa

array([3, 3, 3, 3, 3, 3])

In [16]:
arr

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10])

In [17]:
arr_c = arr.copy()

In [18]:
arr_c

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10])

In [19]:
arr

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10])

In [20]:
arr_c [0:6] = 20

In [21]:
arr_c

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [22]:
arr

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10])

# 2 Dimentional Array

In [23]:
arr_2d = np.array([[25,26,47], [12,45,67],[43,65,76]])

In [24]:
arr_2d

array([[25, 26, 47],
       [12, 45, 67],
       [43, 65, 76]])

In [26]:
arr_2d[1][2]

67

In [27]:
arr_2d[1,2]

67

In [28]:
arr_2d

array([[25, 26, 47],
       [12, 45, 67],
       [43, 65, 76]])

In [36]:
arr_2d[1:3, 1:]

array([[45, 67],
       [65, 76]])

In [37]:
#Boolean array

In [39]:
arr = np.arange(1,10)

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b_arr = arr >5

In [43]:
b_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [44]:
arr[b_arr]

array([6, 7, 8, 9])

In [46]:
arr[arr<3]

array([1, 2])

In [47]:
arr_2d = np.arange(50).reshape(5,10)

In [48]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
arr_2d[3:,5:7]

array([[35, 36],
       [45, 46]])